# Generated by Django 4.0.1 on 2022-01-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='index',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
