# Generated by Django 4.0.1 on 2022-01-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_alter_school_index_alter_school_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10)),
                ('title', models.TextField(unique=True)),
                ('link', models.TextField()),
            ],
        ),
    ]
