# Generated by Django 4.0.1 on 2022-01-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
