# Generated by Django 4.0.1 on 2022-02-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Go',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.TextField()),
            ],
        ),
    ]
